### ISSUE TITLE
ImportError: No module named pash.misc on Linux

### ISSUE THREAD

**Issue by rjousse18** [MattMoony/figaro#14]
I have this error :

`Traceback (most recent call last):
  File "figaro.py", line 3, in <module>
    import pash.misc, pash.cmds, sys
ImportError: No module named pash.misc`

when i launch `python figaro.py`

`
Traceback (most recent call last):
  File "figaro.py", line 3, in <module>
    import pash.misc, pash.cmds, sys
  File "/home/remi/.local/lib/python3.6/site-packages/pash/cmds.py", line 4, in <module>
    from pash.command import Command
  File "/home/remi/.local/lib/python3.6/site-packages/pash/command.py", line 7, in <module>
    def _def_callback(cmd: Command, args: List[str]) -> None:
NameError: name 'Command' is not defined
`

when i launch `python3 figaro.py`

python version : 2.7.17
python3 version : 3.6.9

(event with latest update)

**Comment by MattMoony** [comment]
Hopefully this does the trick ... ^^
My changes to `pash-cmd` and its new release _should_ fix the error you're experiencing ... 
Feel free to reply, if that's not the case!

**Comment by rjousse18** [comment]
even with the last update I have this errors

**Comment by Sentero-esp12** [comment]
I'm getting a similar error:
```
python figaro.py -s
Traceback (most recent call last):
  File "figaro.py", line 3, in <module>
    import pash.misc, pash.cmds, sys
ModuleNotFoundError: No module named 'pash'
```
`Python 3.8.8`
