### ISSUE TITLE
No module named 'pwd'

### ISSUE THREAD

**Issue by LukasDoesDev** [MattMoony/figaro#5]
**Describe the bug**
I got the error while running figaro.py.
Trace:
```
Traceback (most recent call last):
  File "figaro.py", line 3, in <module>
    import pash.misc, pash.cmds, sys
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python36\lib\site-packages\pash\__init__.py", line 1, in <module>
    from .api import ls
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python36\lib\site-packages\pash\api.py", line 3, in <module>
    from .ls_class import LS
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python36\lib\site-packages\pash\ls_class.py", line 2, in <module>
    from .file_info import FileInfo
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python36\lib\site-packages\pash\file_info.py", line 2, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

**To Reproduce**
1. Go to the console and run `python -m pip install -r requirements.txt`.
2. Get an error for pash-cmd.
3. Remove pash-cmd and add pash to requirements.txt.
4. Go to the console and run `python -m pip install -r requirements.txt` again.
5. See the error.

**Expected behavior**
I expected to run the program without any errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2004 (build 19041.630)

**Comment by LukasDoesDev** [comment]
By the way, I cloned the repository and then ran the commands.

**Comment by MattMoony** [comment]
Hi, 

you will have to keep `pash-cmd` in your dependencies - it's a self-written module that cannot be replaced by `pash`.

However, if you do get an error whilst trying to install `pash-cmd`, please file a bug-report on my [GitHub repo](https://github.com/MattMoony/pash) for this module.

Thanks for using Figaro!

... Matthias
