### ISSUE TITLE
Error while installing requirements

### ISSUE THREAD

**Issue by LukasDoesDev** [MattMoony/figaro#6]
**Describe the bug**
I was installing the requirements but i got this error:
```
Collecting argon2-cffi==20.1.0
  Using cached argon2_cffi-20.1.0-cp39-cp39-win_amd64.whl (42 kB)
Collecting asciimatics==1.11.0
  Using cached asciimatics-1.11.0-py2.py3-none-any.whl (96 kB)
Collecting cffi==1.14.0
  Using cached cffi-1.14.0.tar.gz (463 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\lukas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lukas\\AppData\\Local\\Temp\\pip-install-o303ils4\\cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\lukas\\AppData\\Local\\Temp\\pip-install-o303ils4\\cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lukas\AppData\Local\Temp\pip-pip-egg-info-5s1bkn4i'
         cwd: C:\Users\lukas\AppData\Local\Temp\pip-install-o303ils4\cffi\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lukas\AppData\Local\Temp\pip-install-o303ils4\cffi\setup.py", line 127, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\lukas\AppData\Local\Temp\pip-install-o303ils4\cffi\setup.py", line 105, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**To Reproduce**
1. Get Python 3.9 from the Microsoft store.
2. Add that to the path -> `C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0`
3. Run `pip3.9 install -r requirements.txt`

**Expected behavior**
I expected it to install the requirements properly without any errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2004

**Comment by LukasDoesDev** [comment]
Also, do you have a Discord server or something? I would like to ask why you this needs login information.

**Comment by MattMoony** [comment]
Hi!

It looks as though pip is trying to tell you that it needs Microsoft Visual C++ 14.0 in order to properly build code. A website like [this](https://www.scivision.dev/python-windows-visual-c-14-required/) one should provide more info 🙃.

**Comment by MattMoony** [comment]
Sadly I don't currently have a Discord server, however, I might get one in the future ... 🤷 

To still answer your question, however: The login info is needed, because Figaro is/will be designed in such a way that other devices in your LAN (e.g. your phone) have access to Figaro and can therefore control your mic/soundboard. You probably don't want every user in your network to be able to do this 😄.

You shouldn't have to log into the GUI in the future though. As soon as I finish building the frontend and create the Electron app, I will configure it in such a way that the authentication token is automatically created & set - you wont have to log in, if you open the app on the same PC.

Hope this answers all your questions! 😃 Feel free to ask if it doesn't!

**Comment by LukasDoesDev** [comment]
Sounds cool!
